# -*- coding: utf-8 -*-
"""check_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6tlgwOTxS82Y-uluZehhgrguh3utdlS
"""

import random
check = random.randrange(0, 10)

def check_luck(x):
  if x > check:
    print("You got a lower number, Better luck next time!")
  elif x < check:
    print("You got a bigger number, Better luck next time!")
  else:
    return "You won the game"

choice = random.randrange(0, 10)
check_luck(choice)